# Permalinks
permalink:           pretty

# Setup
title:               Proof That I'm Right and You're Wrong
tagline:             A Definitive Data Science Blog
url:                 http://elarson649.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Eric Larson
  url:               https://www.linkedin.com/in/eric-larson-26533687/
  email:             elarson649@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/elarson649

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
